"""add appointments table

Revision ID: 48396a4548de
Revises: 
Create Date: 2024-12-28 21:05:27.303327

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48396a4548de"
down_revision = None
branch_labels = None
depends_on = None

appointment_status = sa.Enum(
    "OPEN", "SCHEDULED", "COMPLETED", "CANCELLED", name="appointmentstatus"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("coach_id", sa.UUID(), nullable=False),
        sa.Column("appointment_time", sa.DateTime(), nullable=True),
        sa.Column("status", appointment_status, nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("student_satisfaction", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointments")
    # ### end Alembic commands ###
